spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ignite-poc
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: postgres

server:
  port: ${PORT:8090}

ignite:
  igniteInstanceName: my-ignite
  dataStorageConfiguration:
    defaultDataRegionConfiguration:
      initialSize: 10485760 #10MB
    dataRegionConfigurations:
      - name: my-dataregion
        initialSize: 104857600 #100MB
  cacheConfiguration:
    - name: person
      writeBehindEnabled: true
      readThrough: true
      writeThrough: true
      queryEntities:
        - schemaName: locals
        - tableName: person
          keyFieldName: id
          keyType: java.lang.Long
          valueType: java.lang.Object
          fields:
            first_name: java.lang.String
            last_name: java.lang.String

